# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LeGrand.io Blog
email: jrlegrand@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is meant to be a companion piece to my exploration of application development as it relates to pharmacy and health IT.
  <br>
  - Joey LeGrand
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://legrand.io/" # the base hostname & protocol for your site
twitter_username: jrlegrand
github_username:  jrlegrand

# Build settings
markdown: kramdown
