# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: code-pharm
email: jrlegrand@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Codepharm is an outlet for sharing things I learn along the way
  as I try to become a better web developer and pharmacist informaticist.
  <br>
  - Joey LeGrand
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jrlegrand
github_username:  jrlegrand

# Build settings
markdown: kramdown